export default [
    {
        id: 'midudev.midu.dev',
        fullName: 'midudev/midu.dev',
        description: 'Blog de noticias sobre desarrollo',
        language: 'HTML',
        forksCount: 3123,
        stargazersCount: 52869,
        ratingAverage: 0,
        reviewCount: 0,
        ownerAvatarUrl: 'https://avatars.githubusercontent.com/u/1561955?v=4',
    },
    {
        id: 'jaredpalmer.formik',
        fullName: 'jaredpalmer/formik',
        description: 'Build forms in React, withot tears',
        language: 'TypeScript',
        forksCount: 1589,
        stargazersCount: 21553,
        ratingAverage: 88,
        reviewCount: 7,
        ownerAvatarUrl: 'https://avatars.githubusercontent.com/u/4060187?v=4',
    },
    {
        id: 'rails.rails',
        fullName: 'rails/rails',
        description: 'Ruby on Rails',
        language: 'Ruby ',
        forksCount: 18349,
        stargazersCount: 45377,
        ratingAverage: 100,
        reviewCount: 2,
        ownerAvatarUrl: 'https://avatars.githubusercontent.com/u/4060187?v=4',
    },
];
